import 'dotenv/config';
import { loadVault } from '../security/apiKeyVault.js';
import { ScoutAgent } from './core/ScoutAgent.js';
import { SearchEngine } from './core/SearchEngine.js';
import { syncToCloud } from './core/deployer.js';
import ollama from './core/ollamaConnector.js';
import { exec } from 'child_process';
import fs from 'fs';
import path from 'path';

loadVault();

const search = new SearchEngine(process.env.SERPER_API_KEY || '');
const scout = new ScoutAgent();

async function generateAffiliatePages() {
    const productsDir = path.resolve('src/products/affiliate/pages');
    if (!fs.existsSync(productsDir)) fs.mkdirSync(productsDir, { recursive: true });

    const topics = ['best ai tools 2026', 'top saas products', 'profitable side hustles', 'crypto trading bots'];
    for (const topic of topics) {
        const slug = topic.replace(/\s+/g, '-').toLowerCase();
        const filePath = path.join(productsDir, `${slug}.html`);
        if (fs.existsSync(filePath)) continue;

        const html = `<!DOCTYPE html>
<html lang="en">
<head><meta charset="UTF-8"><title>${topic}</title>
<meta name="description" content="Discover the best ${topic} — curated by AffiliateEngine">
<style>
  body { font-family: -apple-system, sans-serif; background: #0a0a0a; color: #fff; max-width: 800px; margin: 0 auto; padding: 40px 20px; }
  h1 { color: #00e676; }
  .card { background: #1a1a1a; padding: 20px; border-radius: 12px; margin: 15px 0; border: 1px solid #2a2a2a; }
  .card h3 { margin: 0 0 5px; }
  .card a { color: #00e676; text-decoration: none; }
  .card a::after { content: ' →'; }
</style></head>
<body>
  <h1>${topic.charAt(0).toUpperCase() + topic.slice(1)}</h1>
  <p>Auto-generated by Emerald Engine — affiliate links active.</p>
  <div class="card"><h3>Top Pick</h3><p>Our AI recommends this product based on current trends.</p><a href="#">Check Price on Amazon</a></div>
  <div class="card"><h3>Runner Up</h3><p>High conversion rate across our 50 proxy network.</p><a href="#">View Deal</a></div>
  <div class="card"><h3>New & Trending</h3><p>Recently discovered by market scanner.</p><a href="#">Learn More</a></div>
  <p style="color:#666;margin-top:40px;font-size:0.8em;">Powered by AffiliateEngine — part of Emerald Ecosystem</p>
</body>
</html>`;
        fs.writeFileSync(filePath, html);
        console.log(`[AFFILIATE] Generated page: ${slug}`);
    }
}

async function runCycle() {
    console.log(`[${new Date().toISOString()}] Starting cycle...`);

    exec('./scripts/cleanup.sh');

    await scout.scout();

    const webResults = await search.search("Current SaaS monetization trends 2026");
    const strategy = await ollama.generateThought(
        `Summarize these opportunities into one actionable strategy: ${JSON.stringify(webResults)}`
    );
    if (strategy) console.log("[AI STRATEGY]:", strategy);

    await generateAffiliatePages();

    try {
        await syncToCloud();
        console.log("Cycle complete: deployed to cloud.");
    } catch (e) {
        console.error("Deploy failed:", e.message);
    }
}

async function main() {
    while (true) {
        try {
            await runCycle();
        } catch (error) {
            console.error("[CRITICAL] Cycle failed, restarting immediately:", error);
        }
        await new Promise(resolve => setTimeout(resolve, 60000));
    }
}

main();
