[build]
  command = "echo 'static build complete'"
  functions = "netlify/functions"
  publish = "."

[functions]
  node_bundler = "esbuild"
  included_files = ["src/**/*"]

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/entry"
  status = 200
