[supervisord]
nodaemon=true

[program:intelligence]
command=/app/init_intelligence.sh
autostart=true
autorestart=false
stdout_logfile=/tmp/intelligence.log
stderr_logfile=/tmp/intelligence.log
startretries=3

[program:engine]
command=/app/emerald-engine
autostart=true
autorestart=true
stdout_logfile=/tmp/engine.log
stderr_logfile=/tmp/engine.log
depends_on=intelligence
