[supervisord]
nodaemon=true
user=root

[program:ollama]
command=ollama serve
autostart=true
autorestart=true
stderr_logfile=/var/log/ollama.err.log
stdout_logfile=/var/log/ollama.out.log

[program:node]
command=node src/agi/brain.js
autostart=true
autorestart=true
stderr_logfile=/var/log/node.err.log
stdout_logfile=/var/log/node.out.log
