import { slugify, uid } from '../utils/helpers.js';
import logger from '../utils/logger.js';
import config from '../config.js';
import { injectAdSlots, generateAdBlockWall } from '../monetization/adsense.js';
import affiliateManager from '../monetization/affiliate.js';

export function generatePage(trend, options = {}) {
  const id = uid(8);
  const title = trend?.title || options.title || 'Emerald Landing';
  const slug = slugify(title);
  const adCount = options.adSlots ?? config.AD_SLOT_COUNT;
  const enableAffiliate = options.affiliate !== false;
  const enableAdblockWall = options.adblockWall === true;

  const sections = [
    { type: 'hero', heading: title, sub: 'Built with Emerald — your autonomous micro-SaaS engine.' },
    { type: 'features', items: ['Lightning Fast', 'SEO Optimized', 'Ad Ready', 'Serverless'] },
    { type: 'cta', text: 'Get Started Free' },
  ];

  let rawHtml = buildHTML(title, sections);
  let rawCss = buildCSS();

  const adResult = injectAdSlots(rawHtml, adCount);
  rawHtml = adResult.html;
  const adSlots = adResult.slots;

  if (enableAffiliate) {
    rawHtml = affiliateManager.injectAffiliateLinks(rawHtml, title);
  }

  if (enableAdblockWall) {
    const wall = generateAdBlockWall();
    rawHtml = rawHtml.replace('</body>', `${wall}\n</body>`);
  }

  logger.info(`pageGenerator: generated "${title}" (${slug}) — ${adCount} ads, affiliate:${enableAffiliate}`);
  return { id, slug, title, html: rawHtml, css: rawCss, adSlots, sections, createdAt: new Date().toISOString() };
}

function buildHTML(title, sections) {
  const secHtml = sections.map(s => {
    if (s.type === 'hero') return `<header class="hero">
  <h1>${s.heading}</h1>
  <p>${s.sub}</p>
</header>`;
    if (s.type === 'features') return `<section class="features">
  ${s.items.map(i => `<div class="feature-card"><h3>${i}</h3></div>`).join('\n  ')}
</section>`;
    if (s.type === 'cta') return `<section class="cta">
  <a href="#" class="btn">${s.text}</a>
  <p style="margin-top:1rem;font-size:0.85rem;color:#999">
    💎 <a href="/subscribe" style="color:#667eea">Remove ads — $3/mo</a>
  </p>
</section>`;
    return '';
  }).join('\n');

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>${title}</title>
  <meta name="description" content="${title} — generated by Emerald" />
  <link rel="stylesheet" href="style.css" />
  <script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
  <!-- AD_SLOT_0 -->
  <!-- AD_SLOT_1 -->
  <!-- AD_SLOT_2 -->
</head>
<body>
  <nav class="navbar"><div class="nav-inner"><strong>Emerald</strong> <a href="/subscribe" style="color:#fff;text-decoration:none;float:right;font-size:0.85rem;background:rgba(255,255,255,0.15);padding:0.3rem 0.8rem;border-radius:4px">Upgrade</a></div></nav>
  <main>
${secHtml.split('\n').map(l => '    ' + l).join('\n')}
  </main>
  <footer><p>&copy; ${new Date().getFullYear()} — Powered by Emerald | <a href="/privacy">Privacy</a> | <a href="/terms">Terms</a></p></footer>
  <script>
    window.emerald = { pageId: '${uid(6)}', adSlots: ${config.AD_SLOT_COUNT} };
  </script>
</body>
</html>`;
}

function buildCSS() {
  return `*{margin:0;padding:0;box-sizing:border-box}
body{font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif;line-height:1.6;color:#1a1a2e;background:#f8f9fa}
.navbar{background:#1a1a2e;color:#fff;padding:1rem 2rem}
.nav-inner{max-width:960px;margin:0 auto}
.hero{text-align:center;padding:4rem 2rem;background:linear-gradient(135deg,#667eea,#764ba2);color:#fff}
.hero h1{font-size:2.5rem;margin-bottom:1rem}
.hero p{font-size:1.2rem;opacity:.9}
.features{display:grid;grid-template-columns:repeat(auto-fit,minmax(200px,1fr));gap:1.5rem;padding:3rem 2rem;max-width:960px;margin:0 auto}
.feature-card{background:#fff;padding:1.5rem;border-radius:8px;box-shadow:0 2px 8px rgba(0,0,0,.1);text-align:center}
.cta{text-align:center;padding:3rem 2rem}
.btn{display:inline-block;padding:.8rem 2rem;background:#667eea;color:#fff;border-radius:6px;text-decoration:none;font-weight:600}
.btn:hover{background:#5a6fd6}
.emerald-ad-wrapper{margin:1.5rem auto;text-align:center;min-height:90px;max-width:728px}
.emerald-fallback{border:1px dashed #ccc;border-radius:6px}
footer{text-align:center;padding:2rem;color:#666;font-size:.9rem}
footer a{color:#667eea;text-decoration:none}
.affiliate-link{display:inline-block;padding:0.4rem 1rem;background:#f0f4ff;color:#667eea;border:1px solid #d0d8ff;border-radius:4px;text-decoration:none;font-size:0.85rem;margin:0.25rem}
.affiliate-link:hover{background:#e0e8ff}
@media(max-width:600px){.hero h1{font-size:1.8rem}}`;
}

export default generatePage;
