package main

import (
	"fmt"
	"os"
	"strings"
)

type FusedContainer struct {
	Dockerfile    string
	Supervisord   string
	ProxyCode     string
	Components    []DiscoveredSkill
	ComponentPorts map[string]int
}

func compileFusionDockerfile(skills []DiscoveredSkill, niche Niche) *FusedContainer {
	if len(skills) > 20 {
		skills = skills[:20]
	}

	validated := validateSkillsForFusion(skills)
	if len(validated) == 0 {
		return nil
	}

	ports := assignPorts(validated)

	fc := &FusedContainer{
		Components:     validated,
		ComponentPorts: ports,
	}

	fc.ProxyCode = generateFusionProxy(validated, ports)
	fc.Supervisord = generateFusionSupervisord(validated, ports)
	fc.Dockerfile = buildFusionDockerfile(validated, ports, niche)

	return fc
}

func validateSkillsForFusion(skills []DiscoveredSkill) []DiscoveredSkill {
	var valid []DiscoveredSkill
	for _, s := range skills {
		if s.CloneURL == "" {
			continue
		}
		if strings.Contains(s.FullName, "secret") || strings.Contains(s.FullName, "token") {
			continue
		}
		valid = append(valid, s)
	}
	return valid
}

func assignPorts(skills []DiscoveredSkill) map[string]int {
	ports := make(map[string]int)
	basePort := 9000
	for _, s := range skills {
		ports[s.FullName] = basePort
		basePort++
	}
	return ports
}

func buildFusionDockerfile(skills []DiscoveredSkill, ports map[string]int, niche Niche) string {
	var sb strings.Builder

	sb.WriteString(`# Syntax: Multi-stage fusion build
# Generated by Emerald Engine Cross-Platform Factory

# === Stage 1: Build Go proxy/router ===
FROM golang:1.26-alpine AS proxy-builder
WORKDIR /proxy
COPY proxy.go .
RUN go build -o /fusion-proxy proxy.go

# === Stage 2: Build niche child server ===
FROM golang:1.26-alpine AS child-builder
WORKDIR /child
COPY child.go go.mod ./
RUN go build -o /child-server .

# === Stage 3: Runtime ===
FROM alpine:3.20
RUN apk add --no-cache ca-certificates git supervisor python3 py3-pip nodejs npm curl bash jq

`)

	for i, skill := range skills {
		sb.WriteString(fmt.Sprintf(`
# === Skill %d: %s (%s) ===
# Category: %s | Stars: %d | Language: %s
# Source: %s
RUN mkdir -p /opt/skill_%d && \
    git clone --depth 1 --single-branch %s /opt/skill_%d 2>/dev/null || \
    echo "[FUSION] WARN: Failed to clone %s"
`, i, skill.Name, skill.Category, skill.Category, skill.Stars, skill.Language, skill.Source, i, skill.CloneURL, i, skill.FullName))

		if skill.Language == "Python" || skill.Language == "Jupyter Notebook" {
			if i%3 == 0 {
				sb.WriteString(fmt.Sprintf("RUN cd /opt/skill_%d && [ -f requirements.txt ] && pip install --no-cache-dir -r requirements.txt 2>/dev/null || true\n", i))
			}
		} else if skill.Language == "Node.js" || skill.Language == "TypeScript" || skill.Language == "JavaScript" {
			if i%4 == 0 {
				sb.WriteString(fmt.Sprintf("RUN cd /opt/skill_%d && [ -f package.json ] && npm install --production 2>/dev/null || true\n", i))
			}
		}
	}

	sb.WriteString(`
# === Fusion assembly ===
WORKDIR /app
COPY --from=proxy-builder /fusion-proxy .
COPY --from=child-builder /child-server .
COPY supervisord.conf /etc/supervisor/conf.d/supervisord.conf

# === Environment ===
ENV FUSION_MODE=true
ENV CHILD_PORT=8080
ENV PROXY_PORT=7860
`)

	envEntries := ""
	for i, s := range skills {
		port := ports[s.FullName]
		envEntry := fmt.Sprintf("SKILL_%d_PORT=%d SKILL_%d_NAME=%s SKILL_%d_CATEGORY=%s", i, port, i, s.Name, i, s.Category)
		if i > 0 {
			envEntries += " \\\n    "
		}
		envEntries += envEntry
	}
	if envEntries != "" {
		sb.WriteString("ENV " + envEntries + "\n")
	}

	sb.WriteString(`
# === Ports ===
EXPOSE 7860

# === Entrypoint ===
CMD ["/fusion-proxy"]
`)

	return sb.String()
}

func generateFusionProxy(skills []DiscoveredSkill, ports map[string]int) string {
	var routes strings.Builder
	routes.WriteString(`package main

import (
	"io"
	"log"
	"net/http"
	"net/url"
	"os"
	"strings"
)

var proxyRoutes = map[string]string{
`)
	for i, s := range skills {
		port := ports[s.FullName]
		routes.WriteString(fmt.Sprintf(`	"/skill/%d": "http://localhost:%d",
`, i, port))
	}

	routes.WriteString(`}

func main() {
	port := os.Getenv("PROXY_PORT")
	if port == "" {
		port = "7860"
	}
	childPort := os.Getenv("CHILD_PORT")
	if childPort == "" {
		childPort = "8080"
	}

	childURL := "http://localhost:" + childPort

	http.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		for prefix, target := range proxyRoutes {
			if strings.HasPrefix(r.URL.Path, prefix) {
				proxyRequest(w, r, target)
				return
			}
		}
		proxyRequest(w, r, childURL)
	})

	log.Printf("[FUSION] Proxy listening on :%s (child: %s, %d skill routes)", port, childPort, len(proxyRoutes))
	log.Fatal(http.ListenAndServe(":"+port, nil))
}

func proxyRequest(w http.ResponseWriter, r *http.Request, target string) {
	targetURL, err := url.Parse(target)
	if err != nil {
		http.Error(w, "bad gateway", 502)
		return
	}

	proxy := http.ReverseProxy{
		Director: func(req *http.Request) {
			req.URL.Scheme = targetURL.Scheme
			req.URL.Host = targetURL.Host
			req.Header.Set("X-Forwarded-Host", req.Host)
			req.Header.Set("X-Fusion-Proxy", "emerald-factory")
		},
	}
	proxy.ServeHTTP(w, r)
}
`)
	return routes.String()
}

func generateFusionSupervisord(skills []DiscoveredSkill, ports map[string]int) string {
	var sb strings.Builder
	sb.WriteString(`[supervisord]
nodaemon=true
logfile=/var/log/supervisor/supervisord.log
pidfile=/var/run/supervisord.pid

[program:fusion-proxy]
command=/app/fusion-proxy
autorestart=true
stderr_logfile=/var/log/supervisor/proxy.err.log
stdout_logfile=/var/log/supervisor/proxy.out.log

[program:child-server]
command=/app/child-server
autorestart=true
stderr_logfile=/var/log/supervisor/child.err.log
stdout_logfile=/var/log/supervisor/child.out.log
`)

	for i, s := range skills {
		port := ports[s.FullName]
		startCmd := detectSkillStartCmd(s, i, port)
		if startCmd != "" {
			sb.WriteString(fmt.Sprintf(`
[program:skill_%d]
command=%s
directory=/opt/skill_%d
autorestart=true
stderr_logfile=/var/log/supervisor/skill_%d.err.log
stdout_logfile=/var/log/supervisor/skill_%d.out.log
`, i, startCmd, i, i, i))
		}
	}

	return sb.String()
}

func detectSkillStartCmd(skill DiscoveredSkill, index, port int) string {
	lang := strings.ToLower(skill.Language)

	if skill.Category == CatAPI || skill.Category == CatBot || skill.Category == CatMicroservice {
		switch {
		case lang == "go" || lang == "golang":
			return fmt.Sprintf("cd /opt/skill_%d && go run main.go 2>/dev/null || ./main 2>/dev/null || echo 'no go entrypoint'", index)
		case lang == "python" || lang == "jupyter notebook":
			return fmt.Sprintf("cd /opt/skill_%d && python app.py 2>/dev/null || python main.py 2>/dev/null || python server.py 2>/dev/null || echo 'no python entrypoint'", index)
		case lang == "node.js" || lang == "typescript" || lang == "javascript":
			return fmt.Sprintf("cd /opt/skill_%d && node index.js 2>/dev/null || node server.js 2>/dev/null || npm start 2>/dev/null || echo 'no node entrypoint'", index)
		case lang == "rust":
			return fmt.Sprintf("cd /opt/skill_%d && cargo run 2>/dev/null || ./target/release/main 2>/dev/null || echo 'no rust entrypoint'", index)
		default:
			return fmt.Sprintf("cd /opt/skill_%d && ls -la && echo 'unknown language: %s'", index, skill.Language)
		}
	}
	return ""
}

func fusionStats() map[string]interface{} {
	return map[string]interface{}{
		"engine":         "cross-platform-fusion",
		"max_components": 20,
		"proxy_port":     7860,
	}
}

func (fc *FusedContainer) WriteFiles(dir string) error {
	if err := os.WriteFile(dir+"/Dockerfile", []byte(fc.Dockerfile), 0644); err != nil {
		return err
	}
	if err := os.WriteFile(dir+"/proxy.go", []byte(fc.ProxyCode), 0644); err != nil {
		return err
	}
	if err := os.WriteFile(dir+"/supervisord.conf", []byte(fc.Supervisord), 0644); err != nil {
		return err
	}
	return nil
}
