package main

import (
	"encoding/json"
	"fmt"
	"net/http"
	"os"
	"sync"
	"time"
)

type HeartbeatRecord struct {
	Name      string    `json:"name"`
	URL       string    `json:"url"`
	Status    string    `json:"status"`
	Latency   int64     `json:"latency_ms"`
	LastPing  time.Time `json:"last_ping"`
	FailCount int       `json:"fail_count"`
}

type HeartbeatDaemon struct {
	mu         sync.Mutex
	records    []HeartbeatRecord
	interval   time.Duration
	jitterMax  int
	httpClient *http.Client
	pings      int
	failures   int
	rebuilds   int
	running    bool
}

var heartbeatDaemon *HeartbeatDaemon

func initHeartbeatDaemon() *HeartbeatDaemon {
	hbd := &HeartbeatDaemon{
		interval:  25 * time.Minute,
		jitterMax: 300,
		httpClient: &http.Client{Timeout: 10 * time.Second},
	}
	go hbd.runLoop()
	heartbeatDaemon = hbd
	return hbd
}

func (h *HeartbeatDaemon) runLoop() {
	h.running = true
	time.Sleep(30 * time.Second)
	h.pingAll()

	ticker := time.NewTicker(h.interval)
	defer ticker.Stop()

	for range ticker.C {
		jitter := time.Duration(time.Now().UnixNano()%int64(h.jitterMax)) * time.Millisecond
		time.Sleep(jitter)
		h.pingAll()
	}
}

func (h *HeartbeatDaemon) pingAll() {
	var targets []string
	if orchestrator != nil {
		orchestrator.mu.Lock()
		for _, child := range orchestrator.Children {
			targets = append(targets, child.Name)
		}
		orchestrator.mu.Unlock()
	}

	if len(targets) == 0 {
		return
	}

	for _, name := range targets {
		h.pingChild(name)
	}
}

func (h *HeartbeatDaemon) pingChild(name string) {
	orchestrator.mu.Lock()
	child, ok := orchestrator.Children[name]
	if !ok {
		orchestrator.mu.Unlock()
		return
	}
	url := child.URL
	status := child.Status
	orchestrator.mu.Unlock()

	if url == "" {
		url = fmt.Sprintf("https://huggingface.co/spaces/%s/%s", orchestrator.Username, name)
	}

	start := time.Now()
	resp, err := h.httpClient.Head(url)
	latency := time.Since(start).Milliseconds()

	h.mu.Lock()
	defer h.mu.Unlock()

	record := HeartbeatRecord{
		Name:     name,
		URL:      url,
		LastPing: time.Now(),
		Latency:  latency,
	}

	if err != nil || resp.StatusCode >= 500 {
		record.Status = "down"
		record.FailCount = 1
		h.failures++

		for i, r := range h.records {
			if r.Name == name {
				record.FailCount = r.FailCount + 1
				h.records[i] = record
				goto checkRebuild
			}
		}
		h.records = append(h.records, record)

	checkRebuild:
		if record.FailCount >= 3 {
			go h.triggerRebuild(name)
		}
	} else {
		record.Status = "alive"
		if status == "crashed" || status == "error" || status == "stopped" {
			go h.triggerRebuild(name)
			return
		}
	}

	for i, r := range h.records {
		if r.Name == name {
			h.records[i] = record
			return
		}
	}
	h.records = append(h.records, record)
	h.pings++
}

func (h *HeartbeatDaemon) triggerRebuild(name string) {
	orchestrator.mu.Lock()
	child, ok := orchestrator.Children[name]
	orchestrator.mu.Unlock()
	if !ok {
		return
	}

	fmt.Printf("[HEARTBEAT] Triggering rebuild for %s (state: %s, fails: %d)\n",
		name, child.Status, child.ErrorCount)

	orchestrator.mu.Lock()
	rebuildChild := orchestrator.Children[name]
	rebuildChild.Status = "rebuilding"
	orchestrator.Children[name] = rebuildChild
	orchestrator.mu.Unlock()

	go func() {
		err := orchestrator.restartSpace(name)
		if err != nil {
			fmt.Fprintf(os.Stderr, "[HEARTBEAT] Restart failed for %s: %v\n", name, err)
			orchestrator.mu.Lock()
			if c, ok := orchestrator.Children[name]; ok {
				c.Status = "crashed"
				c.ErrorCount++
				orchestrator.Children[name] = c
			}
			orchestrator.mu.Unlock()
			return
		}

		orchestrator.mu.Lock()
		if c, ok := orchestrator.Children[name]; ok {
			c.Status = "running"
			c.ErrorCount = 0
			orchestrator.Children[name] = c
		}
		orchestrator.mu.Unlock()

		h.mu.Lock()
		h.rebuilds++
		h.mu.Unlock()

		fmt.Printf("[HEARTBEAT] %s rebuilt successfully\n", name)
	}()
}

func (h *HeartbeatDaemon) GenerateCFWorker() string {
	return `// Auto-generated by emerald-engine heartbeat daemon
export default {
  async scheduled(event, env, ctx) {
    const targets = ` + "`" + h.generateTargetsJSON() + "`" + `;
    const results = [];
    for (const target of targets) {
      try {
        const resp = await fetch(target.url, { method: 'HEAD' });
        results.push({ name: target.name, status: resp.status < 500 ? 'alive' : 'down' });
      } catch (e) {
        results.push({ name: target.name, status: 'down' });
      }
    }
    await fetch(env.ENGINE_URL + '/api/heartbeat/callback', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ results, ts: Date.now() })
    });
  }
};
`
}

func (h *HeartbeatDaemon) generateTargetsJSON() string {
	h.mu.Lock()
	defer h.mu.Unlock()
	var targets []map[string]string
	if orchestrator != nil {
		orchestrator.mu.Lock()
		for _, child := range orchestrator.Children {
			targets = append(targets, map[string]string{
				"name": child.Name,
				"url":  child.URL,
			})
		}
		orchestrator.mu.Unlock()
	}
	data, _ := json.Marshal(targets)
	return string(data)
}

func (h *HeartbeatDaemon) GenerateGHAWorkflow() string {
	return `name: Heartbeat
on:
  schedule:
    - cron: '*/25 * * * *'
jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Engine
        run: |
          curl -sf -o /dev/null -w "%{http_code}" ${{ secrets.ENGINE_URL }}/health || true
`
}

func (h *HeartbeatDaemon) Stats() map[string]interface{} {
	h.mu.Lock()
	defer h.mu.Unlock()

	alive := 0
	down := 0
	for _, r := range h.records {
		if r.Status == "alive" {
			alive++
		} else {
			down++
		}
	}

	return map[string]interface{}{
		"pings":    h.pings,
		"failures": h.failures,
		"rebuilds": h.rebuilds,
		"alive":    alive,
		"down":     down,
		"interval": h.interval.String(),
		"running":  h.running,
	}
}

func (h *HeartbeatDaemon) GetRecords() []HeartbeatRecord {
	h.mu.Lock()
	defer h.mu.Unlock()
	out := make([]HeartbeatRecord, len(h.records))
	copy(out, h.records)
	return out
}
